services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=ebd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer_ui
    ports:
      - "8080:8080"
    depends_on:
      - db
