# Generated by Django 5.2.1 on 2025-05-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_authcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcode',
            old_name='user',
            new_name='usuario',
        ),
    ]
