# Generated by Django 5.2.1 on 2025-06-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_authcode_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='presenca',
            field=models.CharField(choices=[('presente', 'presente'), ('ausente', 'ausente'), ('ausencia_justificada', 'ausencia_justificada')]),
        ),
    ]
