# Generated by Django 5.2.1 on 2025-06-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('superintendente-geral', 'superintendente-geral'), ('superintendente-congregacao', 'superintendente-congregacao'), ('secretario-geral', 'secretario-geral'), ('secretario-congregacao', 'secretario-congregacao'), ('professor', 'professor')], max_length=50),
        ),
    ]
