# Generated by Django 5.1.6 on 2025-03-09 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Igreja",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="aula",
            name="data",
        ),
        migrations.AddField(
            model_name="aula",
            name="concluida",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aula",
            name="data_prevista",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="aula",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Diario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data_da_aula", models.DateField()),
                ("alunos_presentes", models.IntegerField()),
                ("alunos_ausentes", models.IntegerField()),
                ("numeros_visitantes", models.IntegerField()),
                ("numeros_biblias", models.IntegerField()),
                ("ofertas", models.BooleanField(default=True)),
                ("dizimos", models.BooleanField(default=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.aula"
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.classe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classe",
            name="nome_igreja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aulas.igreja"
            ),
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                ("data_nascimento", models.DateField()),
                (
                    "nome_igreja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.igreja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("presenca", models.CharField(max_length=8)),
                (
                    "diario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.diario"
                    ),
                ),
                (
                    "selecione_aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.aluno"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("trimestre", models.CharField(max_length=50)),
                ("ano", models.CharField(max_length=50)),
                ("concluido", models.BooleanField(default=True)),
                (
                    "nome_igreja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.igreja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.classe"
                    ),
                ),
                (
                    "selecione_aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.aluno"
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aulas.trimestre",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aula",
            name="trimestre_da_aula",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aulas.trimestre",
            ),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=50)),
                (
                    "nome_igreja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.igreja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.classe"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aulas.usuario"
                    ),
                ),
            ],
        ),
    ]
