# Generated by Django 5.2.1 on 2025-09-04 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='congregacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.congregacao'),
            preserve_default=False,
        ),
    ]
