# Generated by Django 5.2.1 on 2025-09-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_congregacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['aula']},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='congregacao',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['aluno__nome']},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-ano', 'periodo']},
        ),
    ]
