# Generated by Django 5.2.1 on 2025-09-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aluno_options_alter_aula_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={'ordering': ['aluno__nome']},
        ),
    ]
